apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-selfsigned
  namespace: vault
spec:
  dnsNames:
    - '*.vault'
    - '*.vault.vault.svc'
    - '*.vault.vault.svc.cluster.local'
    - '*.vault-internal'
    - '*.vault-internal.vault.svc'
    - '*.vault-internal.vault.svc.cluster.local'
    - localhost
  ipAddresses:
    - 127.0.0.1
  secretName: vault-ha-tls
  issuerRef:
    name: vault-selfsigned
    kind: Issuer
    group: cert-manager.io